Fix "SecurityError: localStorage is not available for opaque origins"
When executing tests within a certain context it will generate this error (this was with jest+babel7+webpack).

 Admittedly I don't have a repro but it took me a bit to figure this out.  I had tried locking in different versions of jsdom and other suggested fixes but this is the only thing that's worked for me.

Here is a reference discussion:
https://github.com/jsdom/jsdom/issues/2304

```
 ● Test suite failed to run

    SecurityError: localStorage is not available for opaque origins


    > 4 | import mapboxgl from "mapbox-gl-js-mock";
        | ^


      at Window.get localStorage [as localStorage] (node_modules/jsdom/lib/jsdom/browser/Window.js:257:15)
      at Object.<anonymous>.exports.extend (node_modules/mapbox-gl-js-mock/node_modules/mapbox-gl/src/util/util.js:154:26)
      at extend (node_modules/mapbox-gl-js-mock/node_modules/mapbox-gl/src/util/window.js:61:10)
      at Object.restore (node_modules/mapbox-gl-js-mock/node_modules/mapbox-gl/src/util/window.js:66:18)
      at Object.require (node_modules/mapbox-gl-js-mock/node_modules/mapbox-gl/src/util/web_worker_transfer.js:16:21)
      at Object.require (node_modules/mapbox-gl-js-mock/node_modules/mapbox-gl/src/source/tile_id.js:5:20)
      at Object.require (node_modules/mapbox-gl-js-mock/node_modules/mapbox-gl/src/util/tile_cover.js:4:28)
      at Object.require (node_modules/mapbox-gl-js-mock/node_modules/mapbox-gl/src/geo/transform.js:8:17)
      at Object.require (node_modules/mapbox-gl-js-mock/classes/map.js:9:17)
      at Object.require (node_modules/mapbox-gl-js-mock/index.js:10:8)
```